sudo: required

services:
  docker

before_install:
  - docker build -t mephisto2120/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mephisto2120/react-test npm run test -- --coverage

after_success:
  - docker build -t mephisto2120/multi-client ./client
  - docker build -t mephisto2120/multi-nginx ./nginx
  - docker build -t mephisto2120/multi-server ./server
  - docker build -t mephisto2120/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mephisto2120/multi-client
  - docker push mephisto2120/multi-nginx
  - docker push mephisto2120/multi-server
  - docker push mephisto2120/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-213382163984
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY